from .multitask_resnet import MultiTaskResNet
from .multitask_resnet_fpn import MultiTaskResNetFPN
# from .multitask_resnet_fpn_learnable_embeddings import MultiTaskResNetFPNLearnableEmbeddings
# from .multitask_resnet_fpn_masked_embeddings import MultiTaskResNetFPNMaskedEmbeddings
from .multitask_resnet_fpn_transformer_decoder import MultiTaskResNetFPNTransformerDecoder
from .singletask_resnet_fpn_parrallel_fc_layers import SingleTaskResNetFPNForParallelFCLayers
from .singletask_resnet_fpn import SingleTaskResNetFPN
from .singletask_resnet_fpn_parrallel_fc_layers_wit_decoder import SingleTaskResNetFPNWithTransformersAndParrallelFCLayers 
from .threetask_resnet_fpn_parrallel_fc_layers_with_decoder import ThreeTaskResNetFPNWithParralellTransformerDecoders
from .fourtask_resnet_fpn_moe_decoder_and_softmax_inputs_detector import FourTaskResNetFPNWithMoEDecodersAndSoftmaxInputs
# from .another_model import AnotherModel

__all__ = ['MultiTaskResNet', 'MultiTaskResNetFPN', 'MultiTaskResNetFPNTransformerDecoder',
           'SingleTaskResNetFPN', 'SingleTaskResNetFPNForParallelFCLayers', 'SingleTaskResNetFPNWithTransformersAndParrallelFCLayers',
           'ThreeTaskResNetFPNWithParralellTransformerDecoders', 'FourTaskResNetFPNWithMoEDecodersAndSoftmaxInputs']
